plugins {
    id 'java'
    id 'application'
}

group = 'replicatedlog'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'replicatedlog.App'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'io.javalin:javalin:6.6.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.18.3'
    implementation 'ch.qos.logback:logback-classic:1.5.16'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test', Test) {
    useJUnitPlatform()
    testLogging {
        events 'passed', 'skipped', 'failed'
    }
}
